### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by piever** [JuliaPlots/AlgebraOfGraphics.jl#13]
Laundry list of things to improve, or questions to discuss.

# TODOs

- [x] Avoid recomputing things. The default grouping strategy is suboptimal: if there are many traces with the same grouping, it will redo the sorting each time. Though, to be honest, I wonder whether there are cases where the sorting is the bottleneck (compared to say actually plotting things). Also column selection can be made more efficient by using `Tables.select` and `Tables.columnindex`, instead of calling `Tables.columns` on the whole table. (mostly fixed by the `Tree` strategy in https://github.com/piever/AlgebraOfGraphics.jl/pull/14)

- [x] Keep column names for labeling axes or legend groups (maybe `extract_column` could return a `NamedDimsArray`). (#24)

- [x] Legend support. (#23)

- [x] Layout support (behind a Require block, https://github.com/piever/AlgebraOfGraphics.jl/commit/477a2b82861d12d064432a1f9a39015550f36fc7)

- [x] Fix odd bugs with categorical variables. If different groups have different unique entries, the categorical conversion screws up (may be fixed from the AbstractPlotting side, see https://github.com/JuliaPlots/Makie.jl/issues/453).

- [x] Add slicing context, i.e. columns are series and similar. (#17)

- [x] Decide on `Series` data layout (tree: https://github.com/piever/AlgebraOfGraphics.jl/pull/14)

- [x] Add devdocs (#21)

## Probably not happening (in favor of deprecating StasMakie)

- Get it to work with `Analysis` from StatsMakie whenever they rely on all the data for some preprocessing (may need to happen on `StatsMakie` side, but can start here using Require).

- Get it to work with `Position.stack`, `Position.dodge` & co (same as above).

**Comment by jkrumbiegel** [comment]
I would add actually creating legends to this. What information does one need to create a legend for a AoG plot? I was thinking about it and it seemed to me that the full plot is only defined once you decide the plotting function, no? So `scatter(trace)` is different than `lines(trace)`. But you need to know which function actually plots a trace in order to create the correct legend, so this is a chicken and egg problem it seems to me. Do you have an idea about this?

**Comment by piever** [comment]
Right now the plotting information is encoded in the metadata, so basically what is passed to `plot` is a list of `AbstractTrace` object, each with their own metadata. This allows to mix and match things using the algebra (i.e. `metadata(Scatter, markersize = 10) + metadata(lines)` and things like that). If the user uses this approach, and only calls `plot` on the result, then there is all the information we need for the legend.

The main downside is the verbosity, but I guess a good trick would be to have lazy objects that can encode plot type and metadata defined in AbstractPlotting (say `Scatter(markersize = 10)`. If we want to be extra conservative, `scatter(a::AbstractTrace)` could even error.

The alternative is that the legend is generated within the call to the `plot!` function [here](https://github.com/piever/AlgebraOfGraphics.jl/blob/master/src/makie_integration.jl#L16). What API do you have in mind for the legend? I actually don't really know how to use legends in Makie.

**Comment by jkrumbiegel** [comment]
aha ok so if I do `metadata(Scatter, markersize = 10)` at least I know we're dealing with scatters, from the traces alone. But how do I know which group has which marker and which color? Because that's what I need to prepare the legend.

In MakieLayout, and I assume this will then be integrated into AbstractPlotting in some form, a legend is backed by a node

```julia
entry_groups::Node{Vector{Tuple{Optional{String}, Vector{LegendEntry}}}}
```

This contains one optional group title and a list of LegendEntries for each group. A LegendEntry is a label plus a variable number of LegendElements, that can be MarkerElements or PolyElements or LineElements, etc. So building a legend with 3 size and 4 color groups separated would look a bit like this:

```julia
entry_groups = [
	("Size", [small_marker, medium_marker, big_marker]),
	("Color", [red_poly, green_poly, blue_poly, orange_poly]),
]
```

**Comment by piever** [comment]
Ah OK, now I understand the question better. So, getting the name of the legend group, i.e. `Optional{String}`, is similar to getting the axis labels (take column names), but not yet implemented. Getting the "drawing info" correctly is slightly trickier.

I've done some cleanup and now the only object the plotting package has to deal with is `AlgebraOfGraphics.Tree`, which is a tree describing all the operations the user wants to do with the data, and `AlgebraOfGraphics.outputs(t::Tree)` gives a list of the traces. But in those traces the info is still encoded as categorical, so it's useless to actually drawing the legend. I need to move the "replace categorical variables with theme variables" outside of the `plot!` function, but should just be a small refactor.

This has the same issue as above if one changes the attributes inside the `plot` call, say `table(iris) * data(col1, col2) * primary(color = col3) * plot(color = newcolors)` and then before plotting we do not know the legend. But I suspect the workflow should be to really just do a `... |> plot` at the end. Maybe the display method for these trees could be changed so that one doesn't even need that.

**Comment by piever** [comment]
If you want to play with it, on current master you can do:

```julia
using RDatasets, AbstractPlotting
using AlgebraOfGraphics: table, data, primary, spec, traces

mpg = dataset("ggplot2", "mpg");
cols = data(:Displ, :Hwy);
grp = primary(color = :Cyl);
scat = spec(Scatter, markersize = 10px)
tree = table(mpg) * grp * cols * scat
palette = AbstractPlotting.current_default_theme()[:palette]

serieslist = traces(tree, palette)
```

gives you a list of `OrderedDict`, each of which iterates pairs of `NamedTuple => Trace`, where the `NamedTuple` has the categorical values of the variable, and the `Trace` specifies the plot (`plottype(t::Trace)` gives the plotting type, then `t.args` and `t.kwargs` are positional and keyword arguments respectively).

I think they are not combined optimally right now, but this is the object one should use for legends IMO. In this case `serieslist` only has one element (you get more if you use `+`):

```julia
julia> serieslist[1]
OrderedCollections.OrderedDict{NamedTuple,AlgebraOfGraphics.Trace} with 4 entries:
  (color = 4,) => Trace{Scatter{...}}(([1.8, 1.8, 2.0, 2.0, 1.8, 1.8, 2.0, 2.0, 2.4, 2.4  …  2.0, 2.0, 1.9, 1.9, 2.0, 2.0, 1.8, 1.8, 2.0, 2.0], Int32[29, 29, 31, 30, 26, 25…
  (color = 5,) => Trace{Scatter{...}}(([2.5, 2.5, 2.5, 2.5], Int32[29, 29, 28, 29]), (markersize = Pixel{Int64}(10), color = RGB{Float64}(0.337255,0.705882,0.913725)))
  (color = 6,) => Trace{Scatter{...}}(([2.8, 2.8, 3.1, 2.8, 2.8, 3.1, 3.1, 2.8, 3.1, 3.1  …  3.4, 3.4, 4.0, 4.0, 2.8, 2.8, 2.8, 2.8, 2.8, 3.6], Int32[26, 26, 27, 25, 25, 25…
  (color = 8,) => Trace{Scatter{...}}(([4.2, 5.3, 5.3, 5.3, 5.7, 6.0, 5.7, 5.7, 6.2, 6.2  …  5.4, 5.4, 5.4, 4.6, 5.0, 5.6, 5.3, 4.7, 4.7, 5.7], Int32[23, 20, 15, 20, 17, 17…
```

I imagine it should be more or less straightforward do make a MakieLayout legend from this.

**Comment by piever** [comment]
I've added `layoutplot` (see [implementation](https://github.com/piever/AlgebraOfGraphics.jl/blob/master/src/makielayout_integration.jl) and [example usage](https://github.com/piever/AlgebraOfGraphics.jl#layout)), to have an initial support for facet plots. As this already returns a complex thing (with various subplots), I imagine it could include a legend by default as well.
