### ISSUE TITLE
Missing features with respect to AlgebraOfGraphics 0.3

### ISSUE THREAD

**Issue by piever** [JuliaPlots/AlgebraOfGraphics.jl#156]
List of things to decide before tagging 0.4:

- [x] The "data-free" `dims` context (#79)
- [x] Axis labeling in "data-based" `dims` context (as in http://juliaplots.org/AlgebraOfGraphics.jl/v0.3.1/generated/tutorial/#Non-tabular-mapping-(slicing-context)) (done at #186)
- [x] Clarify API for categorical data and add NEWS entry (done at #182)
- [x] Confirm that we still support geometries (https://github.com/JuliaPlots/AlgebraOfGraphics.jl/pull/80) and add example

~Adding things in separate layout spots (as in http://juliaplots.org/AlgebraOfGraphics.jl/v0.3.1/generated/statistics/#Examples)~ (not blocking, tracked at #187)
