### ISSUE TITLE
Docs meta issue

### ISSUE THREAD

**Issue by piever** [JuliaPlots/AlgebraOfGraphics.jl#173]
Areas of the docs needing most improvements:

- [ ] [Drawing section](http://juliaplots.org/AlgebraOfGraphics.jl/dev/layers/draw/)
- [ ] [Visual section](http://juliaplots.org/AlgebraOfGraphics.jl/dev/generated/visualtransformations/) (describe how `visual` works instead of just showcasing particular examples)
- [ ] Internals, in particular discuss how to create custom analyses
